<a href="https://colab.research.google.com/github/yogeshkumarrudra/Data_structure/blob/main/pandas02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import pandas as pd;

dct = {
    'name': ['yogesh','rewas', 'mayank','parth'],
    'age': [20,21,19,18],
    'roll':[1,2,3,4]
}
# df = pd.DataFrame(dct)    #creating dataframe
# print(df)                 # just prints
# display(df)               # displays very well
# df1 = pd.DataFrame(dct, index=['a','b','c','d'])    #index handling
# display(df1)
df2 = pd.read_csv('student_data.csv')
display(df2)
# display(df2.head(2))      #from starting
# display(df2.tail(3))      #from last
# display(df2.shape)        #gives the dimension

# df2.info()                #meta-data
# df2.describe()            #

# df2.iloc[0]
# display(df2.iloc[0:6])       #it select range between the 0 index to 6 index row wise  (iloc se [0:6] isme 6-0 jitna number of row banega)

df2.loc[3]        #loc us row ka sara data deta hai

# df2.loc[df2['placement_status']=='Placed',['placement_status','internet_usage','exam_score']].iloc[100:400]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

  placement_status
4           Placed

**assignments_completed**

In [76]:
df2.loc[df2['assignments_completed']==8,['placement_status']].iloc[1:2]

  placement_status
4           Placed

In [112]:
df2 = pd.read_csv('student_data.csv')
ds1 = df2[df2['assignments_completed']>5].iloc[20:50]
display(df2)

ds2 = ds1[ds1['	placement_status']=='Placed']
display(ds2)
# display(ds1[ds1["placement_status"]=='placed'])

# df2['age'] = 20
# display(df2)


# df2 = df2.rename(columns={'assignments_completed':'assign_completed'})
# display(df2)

# df2 = df2.rename(columns={'age':'umar'})

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

KeyError: '\tplacement_status'

In [147]:
df2 = pd.read_csv('student_data.csv')
display(df2)

# df3 = df2.drop('previous_score',axis=1)
# display(df3)
# df4 =df2.drop([0,2])
# display(df4)

# df2.sort_values('study_hours')
# # or
# df2.sort_values(by = ['sleep_hours','study_hours'])

df2['attendance'].unique()

df2.agg()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

array([ 56,  69,  60,  99,  52,  40,  86,  72,  77,  64,  65,  98,  67,
        76,  80,  96,  88,  87,  47,  95,  51,  44,  63,  45,  71,  81,
        42,  58,  82,  68,  89,  41,  48,  85,  75, 100,  59,  43,  54,
        55,  50,  94,  93,  73,  61,  90,  66,  49,  97,  70,  84,  74,
        92,  46,  91,  83,  79,  78,  57,  62,  53])