<a href="https://colab.research.google.com/github/yogeshkumarrudra/Data_structure/blob/main/Pandas03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv('student_data.csv')
display(df)

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [14]:
# df.groupby('placement_status')['placement_status'].agg('count')

# df.groupby('placement_status')['sleep_hours'].agg('count')

# df.groupby('placement_status')['exam_score'].agg('mean')
#1. groupby/ cageroticol data
#2. jiska data chaiya
#3. jispe function apply karna hai

# df.groupby('placement_status')['study_hours'].agg('mean')

df.groupby('study_hours')['exam_score'].agg('mean')

study_hours
1     71.264562
2     75.169142
3     78.974939
4     81.845483
5     84.964142
6     88.620043
7     90.539568
8     93.297697
9     95.462126
10    96.574628
11    97.303283
Name: exam_score, dtype: float64